### ISSUE TITLE
Google Earth : Get rid of dependence on PyKML

### ISSUE THREAD

**Issue by donnacalhoun** [clawpack/visclaw#129]
PyKML is really nice!  But do we really need it?  The KML code is short enough that we could just create strings and supply them with customized variable values where needed. 

Altenatively, current HTML code could require lxml library - might make visclaw code cleaner?  The lxml/pykml libraries are easilly installed in anaconda, or through MacPorts, etc.

**Comment by donnacalhoun** [comment]
I don't have plans to remove the dependency on KML - it is easy to install and makes writing kml files very easy.  Someone else is welcome to remove the dependency, if they'd like.

**Comment by mandli** [comment]
Perhaps this should remain open in the event someone would like to take on this task although I think it is a low priority and not something that would keep Google Earth support from being merged.

**Comment by donnacalhoun** [comment]
I am becoming more enamored with PyKML , and so am going to argue that we should keep it.  I realiize this means extra work for the user, but (1) it installs easily with `pip install` (can't say the same for the file it depends on - `lxml`. Using `pip install lxml` results in a setup doesn't play well with Anaconda - use `conda install lxml` instead) and (2) it makes it easier to write KML that validates against schemas (see how I used it in `regions2kml` to get the resulting `regions.kml` to pass the `xmllint` test).

**Comment by mandli** [comment]
I think keeping the dependency is fine if you want to close this.

**Comment by donnacalhoun** [comment]
Awesome!
