### ISSUE TITLE
Google Earth : Create an index.html file that can be loaded using the Google Earth web plugin

### ISSUE THREAD

**Issue by donnacalhoun** [clawpack/visclaw#133]
Create an index.html file that loads the GE Plugin (via javascript) and associated user doc.kml. This will allow users to embed a GE simulation into their webpages

Example : (note that some strings are customized)

```html
<!DOCTYPE html>
<html>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<head>
<title>Google Earth visualization</title>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>

// This should be made a variable
var url = 'http://math.boisestate.edu/~calhoun/visclaw/GoogleEarth/doc.kml'

if (!/http/.test(url)) alert('Please upload this directory to a web hosting!');

//load google earth API
google.load("earth", "1");
var ge = null;

function init()
{
google.earth.createInstance("map", initCallback, failureCallback);
}

function initCallback(object)
{
ge = object;
ge.getWindow().setVisibility(true);
var link = ge.createLink('');
link.setHref(url);
var networkLink = ge.createNetworkLink('');
networkLink.set(link, true, true); // Sets the link, refreshVisibility, and flyToView
ge.getFeatures().appendChild(networkLink);
}

function failureCallback(object) {
//Callback can contain any code to deal with a failure to create the plugin instance.
}

//Returns base url to your app.
function basePath() {
var uri = window.location.href;
return uri.substr(0, uri.lastIndexOf('/') + 1);
}
</script>
<style>
div {width:100%}

#map {width:100%;
height:600px}

#credit {position:center;
          width:500px;
          padding:0px;
	  align:center}
</style>
</head>
<body onload='init()'>
<center>
<div id="map"></div>
<div id="credit">Google Earth KML SuperOverlay generated with
<a href="http://www.gdal.org">GDAL</a></div>
</center>
</body>
</html>
```

**Comment by donnacalhoun** [comment]
I am wondering how much effort  to put into setting things up for the GE web-plugin.  The plugin is going to be [deprecated](https://developers.google.com/earth/) end of this year, and it isn't clear that it will be replaced.   Maybe it will have be enough to rely on screen shots and downloadable lightweight .kmz files (with url links to images) to anyone who might be interested in particular results.  

On the other hand, I don't think it would be very hard to make available a `index.html` file (such as the above) that users could link from a webpage.

**Comment by mandli** [comment]
I would say do it if it is easy but to not worry too much about it.

**Comment by donnacalhoun** [comment]
I've included a plotfigure attribute "kml_url" to allow the user to specify a URL location where image files will eventually be published. These remote links will go into a second (the first is stored in the KMZ file ) KML file that can be easily linked via web or whatever.    The KMZ file will still contain all of the image files, but can be unzipped to a server for remote access.    Opening the KMZ file in GE will still require local access to the files.  Only the KML file will contain the remote links.

If the user does not supply "kml_url" then no second KML file will be created.

**Comment by mandli** [comment]
Can relative URLs be used instead?  If not I think this is ok although annoying if one forgets to add this.

**Comment by donnacalhoun** [comment]
Sure - the user can put anything in as a "URL" (although probably this should be tested).

**Comment by mandli** [comment]
I guess I was thinking that we could do this for them since we know where things are relative to one another although maybe I am not quite getting what you are referring to.

**Comment by donnacalhoun** [comment]
The  KMZ file stores a `doc.kml` file (the `index.html` of KML), which contains  relative references to all the images (stored in subdirectories, also in the KMZ file).   The `kml_url` setting doesn't change this.     

If the user sets `kml_url`, to something, then a second file (`_GoogleEarthfigN.kml`) is created, which, is identical to the `doc.kml` file stored in KMZ, with the exception that a path is provided to the subdirectories containing the image files, etc.  Everything below this file is relative.  

Hopefully, I can explain this in the documentation so that this is clear.

**Comment by mandli** [comment]
Ok, I see what the difference is.

**Comment by donnaaboise** [comment]
I don't think I am going to get around to the GE plugin, especially since it is going to be unplugged in 6 months.  I'd like to close this issue ...

**Comment by mandli** [comment]
Good idea.
