### ISSUE TITLE
Google Earth : Documentation

### ISSUE THREAD

**Issue by donnacalhoun** [clawpack/visclaw#134]
Add documentation to Visclaw webpages!

**Comment by donnacalhoun** [comment]
I've started a googleearth branch in the doc repo.     The documentation page I've started is at
googleearth_plotting.rst.

**Comment by donnaaboise** [comment]
Documentation is in good shape -  I think this issue can be closed.

**Comment by mandli** [comment]
Documentation is never done (which is why I avoid it probably).

Given the state of other documentation however, I think this should be closed.
