### ISSUE TITLE
Google Earth : Improve / merge with geoclaw/kmltools

### ISSUE THREAD

**Issue by rjleveque** [clawpack/visclaw#135]
The file `geoclaw/src/python/geoclaw/kmltools.py` contains some tools I wrote for plotting regions and gauges specified in `setrun.py`, useful for visualizing how a problem is set up before doing a run.  These are also used in `geoclaw/src/python/geoclaw/fgmax_tools.py` for viewing the fixed grid regions used to monitor quantities such as maximum flow depth or velocity over the entire run.  They could probably be improved, and need to be documented.

I put those in geoclaw rather than visclaw since they are fairly specific to geoclaw simulations.  The same is true of the tools created by @donnaaboise, so we should decide where they belong and probably keep them together.  visclaw might be the better place.

**Comment by donnacalhoun** [comment]
I've looked over kmltools, and it should be fairly easy to incorporate them into the GE stuff I have done.  I would basically add a reference to the regions.kml and gauges.kml files into the main .KML/.KMZ files.  

I was wondering about a few things, however : 

* What should be checked to make sure that regions or gauges have been specified?  Should the associated KML files be then generated automatically?

* Once in GE, users can easily turn on or off the regions and gauges.  But do you think there should an option (possibly another plotfigure attribute) that at least turns on/off the initial viewing?  Or maybe we set them off by default? 

* Do you expect that users would want to call box2kml and quad2kml on their own? Or are these utilities only for generating the regions.kml file?

**Comment by rjleveque** [comment]
I sometimes include calls to the kmltools in `setrun.py` so that the regions.kml and gauges.kml get automatically regenerated by `make .data`.  This is handy when trying to set up a problem.  I haven't thought about what default is best in `setplot.py` since I haven't used them that way.

I do use `box2kml` if I just want to quickly put an arbitrary box on GE, e.g. to help figure out what regions to specify in `setrun.py` or to create a figure.

**Comment by donnacalhoun** [comment]
I've added links to regions.kml and gauges.kml in the main GE file.   Nothing bad happens if those files aren't available.  I won't include them in the .KMZ file for now (that would require checking if they exist, etc, and I am not sure my python skills are up to that yet), but if they "somehow" should appear in the plots directory, GE should pick them up.  

I'll  also include links to box and quad files - it is no big deal to switch them off. 

I'll set the default location to be the working directory.   This is of course easy to change.

**Comment by donnacalhoun** [comment]
I noticed that unless the plots are created with a transparent background, the simulation data hides the gauges/regions.  This is probably an easy adjustment to the altitude settings on these place marks.

**Comment by donnacalhoun** [comment]
I figured out how to get the gauge file name into the right place so now KML gauge Placemarks can automatically load gauge PNG files.  Still needs more testing, but I am waiting for a few more examples with gauges.  (my tohoku example broke recently ...)

**Comment by mandli** [comment]
Do you want another example?  Also, what has gone wrong with your Tohoku example?

**Comment by donnacalhoun** [comment]
I wasn't able to run the Tohoku example recently - something with dumpgauges.  But  this is no doubt related to an earlier geoclaw issue.  But in fact, I didn't need to rerun the code to get gauge output. So I can use this app as an example with multiple gauges.  
Do you have another example I could test?

**Comment by mandli** [comment]
There are the storm surge test cases if you want to take a crack at that.  The `dumpgauges` problem, if newer, has a fix waiting in the wings.

**Comment by donnacalhoun** [comment]
The kmltools file `gauges2kml` is now called automatically when the KMZ/KML files are built.  The file `gauge.kml` is stored and linked in the KMZ file, as well as in the remote KML file.  This hasn't been extensively tested, so if anyone has a file with multiple gauges, please give this a try.   

What is the status with regions?  It wouldn't be too hard to create the KML file for these automatically.

**Comment by mandli** [comment]
In that they exist or that they will change?

**Comment by donnacalhoun** [comment]
I was just referring to Randy's tools to create a KML files to show the outline of regions in GE.  This routine `regions2kml` could also be called automatically, and regions could be available in the GE vis stuff as well.  (in fact, it is already in their, but the file is not created automatically).  I may just add this. 

But it seems that `box` and `quad` are more for setting up an initial region, rather than for vis purposes.  is that right?

**Comment by donnacalhoun** [comment]
I removed the dependencies on setrun.py - and now read just read the regions.data, claw.data and gauges.data files (these are always created in outdir, right?)    I have mostly left Randy's original routines alone, but brought in a lot of the functionality into the plotpages stuff.    The logic of handling the interactive case and the call from plotpages in the same routine was getting complicated.   
I think this issue can be closed - although certainly there could be work to do at a future hackathon ...
