### ISSUE TITLE
Inconsistent Handling of File Format Specification

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#140]
I think the way we decide which file format to try when plotting is not consistent (or at least I cannot see how it works).  When `plotclaw` is called it contains a `format` key word argument which is then used by default and sent through the `plotpages.plotclaw_driver` which does replace it.  Although this is pretty confusing, this actually works save for the spot where it tries to use `plotdata.gettime` which also takes a format argument and uses the default one passed through rather than the one in `plotdata`.  Simple fix to line 1753 of `plotpages` but I am thinking that we need to rethink how we want to specify the file format being used.

**Comment by mandli** [comment]
As an aside, this is also done in https://github.com/clawpack/pyclaw/blob/master/src/pyclaw/plot.py, mainly to adhere to the `plotclaw` interface.

**Comment by ketch** [comment]
In general, I think that file reading is too intertwined with the rest of visclaw.  It's hard to use visclaw to plot a Solution from memory because reading files is such a persistent assumption.  I've done a little to change this, but it would be nice to make the plotting routines not care at all about whether you have a file or something already in memory.

**Comment by mandli** [comment]
I agree, it would be best to abstract this so that the visualization assumed only that it had a `solution` or `state` even.  Perhaps closing this issue and raising another with that design goal would be good.  Another idea I have been having lately is to create a wiki page here on github specifically for a "wish-list" of things we would like to change in VisClaw so we do not rediscover these types of things and they are all in one place.  Perhaps we can start to outline a refactor that could start to be done piece by piece rather than as a whole which at least has been a stumbling block for my attempts.

**Comment by rjleveque** [comment]
This discussion is out of date.  Raise a new issue if there's still a problem.
