### ISSUE TITLE
Add ability to plot using more than one thread

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#164]
Plotting can get pretty slow for some of the complex AMR applications and it would be nice to have the ability to speed this up.  One way that would be easy to do this is to add the ability to spread the plotting abilities out to a group of sub-processes, mainly thinking of a thread pool here, and have the team go through each frame and plot whatever is on the top of the stack.  This may involve doing some changes to `clawutil` as well.

**Comment by ketch** [comment]
This has been implemented.
