### ISSUE TITLE
Fix Path to `gauge.data` file

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#166]
we have it in two places - the top directory, and the _output file. The plotting programs use the gauges.data in the top one, and the fort.gauges output from the _output dir. I suggest it be changed to use the _output only directory for both files, so that new runs with different gauges can be done at the same time as plotting. why do we even need it in the top dir?

**Comment by mandli** [comment]
This was moved from clawpack/geoclaw#175 to here as the relevant code is in visclaw.

**Comment by rjleveque** [comment]
All the .data files get created in the top dir when `make data` is executed and then are copied to `_output` when `make .output` is executed.  The plotting should take this data from the same place it's getting the output as suggested by @mjberger.  See PR #167 for a fix.

**Comment by rjleveque** [comment]
Apparently fixed in #167.
