### ISSUE TITLE
Interactive Plotting Only Plots First Figure

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#182]
I ran into this when working with @mjberger yesterday and just saw this again on my own machine with a completely different example.  I am not sure when this started happening but my suspicion is that the parallel plotting may have caused something to break.

**Comment by rjleveque** [comment]
I've noticed this too -- you have to quit out of the Iplotclaw loop and give the show() command and then restart the loop, after which everything is fine.  Maybe it's in the parallel plotting changes, I haven't investigated yet.

**Comment by ketch** [comment]
I've had this issue for a long time, but only on one machine, so I figured it was some problem with my matplotlib install there.  Can't test now because I'm traveling, unfortunately.  It would be great to know if other users see the same or not.

**Comment by mandli** [comment]
I just noticed that commenting out frametools.py:138 `plt.ioff()` seems to fix things.  @rjleveque do you remember why we needed to turn interactive off at that point?  Commenting this out does not seem to break anything that I have noticed (yet).

**Comment by rjleveque** [comment]
No, I don't remember, but `git diff` shows that this hasn't changed since at least v5.1.0 more than 2 years ago so I don't think this is the cause of the recent change in behavior.  I'll try removing it from my copy and see if I run into any problems.

**Comment by mandli** [comment]
I actually wonder if it's something that may have changed in the builds of matplotlib we are using although I think @ketch mentioned this behavior awhile ago?
