### ISSUE TITLE
Inconsistency in plot_show functionality

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#19]
There seems to be an inconsistency in how plot_show is used in VisClaw.  `show` itself can be done through matplotlib but if one would want to only plot a particular level of data in AMR `amr_plot_show` was the way to do it before.  It looks like this was left in the 1d plotting but not the 2d version.

**Comment by rjleveque** [comment]
@mandli: isn't this the `amr_data_show` attribute?  Is this still an issue?

**Comment by mandli** [comment]
Probably?  I would have guessed that as well.  Closing.
