### ISSUE TITLE
cStringIO deprecated in Python 3

### ISSUE THREAD

**Issue by rjleveque** [clawpack/visclaw#200]
`src/python/visclaw/JSAnimation/html_writer.py` uses `cStringIO`, which has been deprecated in Python 3, see e.g. http://stackoverflow.com/questions/28200366/python-3-4-0-email-package-install-importerror-no-module-named-cstringio

@ketch: I think we dealt with this someplace else in Clawpack already with a good way to deal with the different versions, but I can't remember where now...

**Comment by ketch** [comment]
This is more difficult than I expected.  I have a version that runs here:

https://github.com/ketch/visclaw/blob/python3_html_writer/src/python/visclaw/JSAnimation/html_writer.py

However, the animation images and the control icons just show up as broken links, so this is useless so far.

**Comment by ketch** [comment]
This got fixed in https://github.com/clawpack/visclaw/commit/3f9b25a3f39ad411ea56d47f3b5c628ad2966406.  Closing.
