### ISSUE TITLE
Gauges Are Included in Movies if `figno` is Not Set Explicitly

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#218]
See https://github.com/clawpack/geoclaw/pull/271 for a description of the problem

**Comment by rjleveque** [comment]
It worked ok to remove all figno's in a different example (amrclaw/examples/advection_2d_square) so I'm not sure what went wrong in the geoclaw example.

**Comment by mandli** [comment]
Does it only not work in the multilayer case?

**Comment by rjleveque** [comment]
I've only tried those two cases, so I can't generalize.

**Comment by mandli** [comment]
It also appears to happen in the chile2010 example if a `figno` is not assigned for any of the plots.

**Comment by mandli** [comment]
Furthermore I cannot reproduce it in AMRClaw (I tried the Burgers 2D and advection swirl examples).

**Comment by ketch** [comment]
@mandli, can we close this?  I see that https://github.com/clawpack/geoclaw/pull/271 was merged.

**Comment by mandli** [comment]
Yes.
