### ISSUE TITLE
auto-detect output file type rather than setting `plotdata.format`

### ISSUE THREAD

**Issue by rjleveque** [clawpack/visclaw#221]
This should perhaps be done in pyclaw rather than visclaw.  

See the discussion at #220.

**Comment by brandon1780** [comment]
Push

**Comment by brandon1780** [comment]
#220

**Comment by brandon1780** [comment]
Duplicate of #

**Comment by ketch** [comment]
Update: #220 is closed; the relevant PR is https://github.com/clawpack/visclaw/pull/222.
