### ISSUE TITLE
Use JSAnimation directly from matplotlib

### ISSUE THREAD

**Issue by ketch** [clawpack/visclaw#223]
I discovered today that JSAnimation was merged into matplotlib version 2.1, last fall.  We should switch over to using this.  As far as I can tell, they fixed the issue where you would sometimes get a javascript error instead of the animation (hooray!)  You will need to update to matplotlib 2.1+ for this to work.  There is a modified version of animation_tools.py in clawpack/riemann_book (currently in a PR) that can be backported to visclaw (and we can delete the JSAnimation directory).

**Comment by mandli** [comment]
I am glad this capability has been merged in and we don't need to keep our own version (which is behind the newest version as well).

**Comment by ketch** [comment]
Any opinions on when to make this change?  It will break things for people using Matplotlib < 2.1.0, which was released in October 2017.  I think it would be nice to include this change in the next release of Clawpack, which I guess is coming very soon.

**Comment by mandli** [comment]
+1.

**Comment by ketch** [comment]
If you have a branch and want to push it and mention what's not working, I can also take a look.

**Comment by rjleveque** [comment]
Closing this issue for now since we ran into problems using JSAnimation from mpl.  Something to consider again in the future perhaps..
