### ISSUE TITLE
visclaw/src/matlab/plotframe2.m  not plotting correctly

### ISSUE THREAD

**Issue by temaltba** [clawpack/visclaw#254]
I am trying to plot 3 levels of refinement using a pcolor plot. The figure pops up and is completely blank. I have isolated the issue to lines 384 and 385. 

  (380)       % Increase it sligtly to make sure that we can see all the patches
  (381)       % plotted at the different z levels. 
  (382)       % Also, make sure the zero level is visible (so user can add
  (383)       % curves, etc to plot).
  (384)     zlim = [min(zlim)-0.001 0+0.001];
  (385)     set(gca,'zlim',[-maxlevels-1,0]);

If I comment out these lines, the plots look great.

**Comment by mandli** [comment]
This code makes a slight adjustment to the plotting levels so that `z=0.0` is included as is often assumed to be an important point in tsunami and other plotting.  Are you plotting values that are not centered at `z=0`?

**Comment by temaltba** [comment]
I see. I am not. My solution is strictly positive for all time.

**Comment by mandli** [comment]
Have you tried to explicitly set the colorbar limits?

**Comment by temaltba** [comment]
It seems to be working fine (when compared to python plotting) if I comment out lines 384 and 385, and replace them with the standard:
        set(gca,'ZLimMode','auto');
        zlim = get(gca,'zlim')

**Comment by mandli** [comment]
Did you get this all to work now?

**Comment by temaltba** [comment]
Yes. It's working just fine.
