### ISSUE TITLE
Issue with 3d AMR plotting: readamrdata_ascii.m

### ISSUE THREAD

**Issue by temaltba** [clawpack/visclaw#258]
I ran code for an AMRclaw (version 5.6.1 problem) for one equation with three auxiliary variables without any issues. I am now trying to plot slices of the data using plotclaw3.m in visclaw, which reads in ascii files. I received the following error:
Subscripted assignment between dissimilar structures.
Error in readamrdata_ascii (line 99)
    amr(ng) = amrdata;
Error in readamrdata (line 84)
        [amr,t] = readamrdata_ascii(dim,Frame,dir,readblocknumber);
Error in plotclaw3 (line 97)
        [amrdata,t] = readamrdata(clawdim,Frame,outputdir,outputflag,...

Anyone had issues with this? I've tried making small changes to readamrdata_ascii.m without any success.

**Comment by mandli** [comment]
@donnaaboise Do you have an idea on this?

**Comment by donnaaboise** [comment]
The problem may be that you need to make sure ReadBlockNumber = 0.  This is normally set in `setplot2.m`.

**Comment by donnaaboise** [comment]
Do you have ReadBlockNumber set?  Normally, this is set in the setplot2.m file.  For AMRClaw runs, it should be set to 0. 
-----------------------------------
Donna Calhoun
Associate Professor
Department of Mathematics, Mathematics Bldg 241A
Boise State University
1910 University Drive
Boise, ID 83725-1555
(208) 426-3386
http://math.boisestate.edu/~calhoun
-----------------------------------

**Comment by temaltba** [comment]
I tried setting that in setplot2 and setplot3 without success. That being said, I ran multiple 2d AMRclaw problems and successfully plotted without having set ReadBlockNumber = 0 in setplot2.

**Comment by donnaaboise** [comment]
I see the problem. 

Line 44 (readamrdata_ascii.m) should be : 

    amr_s = struct('gridno',[],'level',[],'blockno',[],...
        'mx',[],'my',[],'mz',[],'xlow',[],'ylow',[],'zlow',[],...
        'dx',[],'dy',[],'dz',[],'data',[]);

(remove the ‘q’ entry (last entry) in the struct).   

I’ll issue a PR for this change. 

Donna

-----------------------------------
Donna Calhoun
Associate Professor
Department of Mathematics, Mathematics Bldg 241A
Boise State University
1910 University Drive
Boise, ID 83725-1555
(208) 426-3386
http://math.boisestate.edu/~calhoun
-----------------------------------

**Comment by temaltba** [comment]
Thanks. It's working now.
