### ISSUE TITLE
`make plots` is slow

### ISSUE THREAD

**Issue by giboul** [clawpack/visclaw#307]
Hi! I' new here but I'd like to make a suggestion.

The `make plots` command can be frustratingly long when debugging. A faster solution would be to use `Iplotclaw` but I did not appreciate having to use the terminal at the same time (and having to minimize windows because I have a small screen).

So I wrote a small script making use of the [`plotframe(..., refresh=True)`](https://github.com/clawpack/visclaw/blob/master/src/python/visclaw/frametools.py#L42) function and matplotlib's [mpl_connect](https://matplotlib.org/stable/api/backend_bases_api.html#matplotlib.backend_bases.FigureCanvasBase.mpl_connect) to change frames with just the arrow keys. I ended up adding numerical input (press 49 then press enter to show frame 49) and a FuncAnimation when passing the `FPS=<some_frames_per_second_value>` argument to `make iplot`.

Could this be a good addition to visclaw? Here my code

```Python
from pathlib import Path
from argparse import ArgumentParser
from matplotlib import pyplot as plt
from matplotlib.animation import FuncAnimation
from clawpack.visclaw.Iplotclaw import Iplotclaw
from clawpack.visclaw.frametools import plotframe


def interactive_plot(fps=0, **kwargs):
    """Take advantage of Iplotclaw to make an interactive plotting session."""
    ip = Iplotclaw(**kwargs)
    counter = dict(current=0, max=0, right=1, left=-1, up=1, down=-1)
    counter["max"] = len(list(Path(ip.plotdata.outdir).glob("fort.q*")))

    def update(i):
        plotframe(i, ip.plotdata, simple=ip.simple, refresh=True)
    update(0)

    def arrow_key(event):
        """If pressed key is in counter, increment index and update plot."""
        if event.key in counter:
            counter["current"]=(counter["current"]+counter[event.key])%counter["max"]
            update(counter["current"])

    frame = dict(n="")
    def to_frame(event):
        if event.key.isnumeric():
            frame["n"] += event.key
        elif event.key == "enter":
            counter["current"] = int(frame["n"] or 0)
            frame["n"] = ""
            update(counter["current"])


    if fps:
        anim = FuncAnimation(plt.gcf(), update, frames=counter["max"], interval=1e3/fps)
        return anim
    else:
        for fn in plt.get_fignums():
            plt.figure(fn).canvas.mpl_connect('key_press_event', arrow_key)
            plt.figure(fn).canvas.mpl_connect('key_press_event', to_frame)


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("fps", default=0, type=float)
    args = parser.parse_args()
    anim = interactive_plot(**args.__dict__)
    plt.show(block=True)
```

And this is what I added to the `Makefile.common` in `clawutil` to have it avaliable from any folder:

```Makefile
FPS = 0
iplot:
	$(CLAW_PYTHON) $(CLAW)/visclaw/src/python/visclaw/arrowkeyplot.py $(FPS)
```

So for example, here are the possible uses of the above code:
- Run `make iplot` then...
   * Enter some frame number (say `10`) then press `enter` (carriage return) to show the 11th frame (frame index 10).
   * then use the left/right or up/down arrow keys to navigate through the frames.
- Run `make iplot FPS=10` and watch a looping animation.

The `plt.show()` command is outside the function so that one is free to import the `interactive_plot` function and either show it later or save the `FuncAnimation`.

*Edit*: I forgot to mention the main advantage of this script: you don't have to wait for the figures to be saved in `.png`,  `.html` and `.tex`! I find that step painful when debugging.

**Comment by mandli** [comment]
This looks great!  Two thoughts:
1. Lets add a `make iplot` target to the makefiles as a shortcut for doing interactive plotting in general.  This maybe should default still to simply running `ipython $CLAW/visclaw/src/python/visclaw/ipyclaw.py` but we can then allow arguments to be passed as you suggested.
2. Add to `$CLAW/visclaw/src/python/visclaw/Iplotclaw.py` and `$CLAW/visclaw/src/python/visclaw/ipyclaw.py` the functionality you have outlined above and have it triggered as a command line argument.  We should probably make the command line options more robust by using `ArgumentParser` in any case.

**Comment by giboul** [comment]
Thanks for your feedback, here's what I tried:

1. I did not manage to pass command line arguments through ipython so keeping the animation option could require an additional command:
```Makefile
fps = 1 
fname = "movie.gif"
anim:
    python $(CLAW)/visclaw/src/python/visclaw/ipyclaw.py --fname $(fname) --fps $(fps)

iplot:
    ipython $(CLAW)/visclaw/src/python/visclaw/ipyclaw.py
```

2. As for ading the functionality to `Iplotclaw`, I tried to use the `cmd` commands with `do_...`, both the keys and the terminal prompt can be used in parallel now.
The best I could do to bind the arrow keys was to add some lines in `Iplot.preloop`:

```Python
class Iplot(cmd.Cmd):
    def preloop(self):
        ...
        if makeplot:
            self.plot_and_cache(self.frameno)
            # Bind keys
            for fn in plt.get_fignums():
                plt.figure(fn).canvas.mpl_connect('key_press_event', self.on_arrowkey_press)
                plt.figure(fn).canvas.mpl_connect('key_press_event', self.on_numeric_input)
        ...
```

Adding the functionality required some more initialization and two more methods.

```Python
class Iplotclaw(Iplot):
    def __init__(..., fps=None, fname=None):
    ...
        # Count number of frames
        self.num_frames = len(list(Path(plotdata.outdir).glob("fort.q*")))

        # Create animation and exit is asked
        if fps is not None or fname is not None:
            from matplotlib import pyplot as plt
            from matplotlib.animation import FuncAnimation
            fname = fname or "movie.gif"
            fps = fps or 1
            def update(i):
                frametools.plotframe(i, self.plotdata, simple=self.simple, refresh=True)
            update(0)
            anim = FuncAnimation(plt.gcf(), update, frames=self.num_frames, interval=1e3/fps)
            anim.save(fname)
            exit()

        # Set arrowkey actions
        self.arrowkeys = dict(right=self.do_n, left=self.do_p, up=self.do_n, down=self.do_p)
        self.frameno_input = ""

        ...

    # Define matplotlib key press actions
    def on_arrowkey_press(self, event):
        """If pressed key is in arrowkeys, increment index and update plot."""
        if event.key in self.arrowkeys:
            self.arrowkeys[event.key](...)
            print("\n"+self.prompt, end=" ")

    def on_numeric_input(self, event):
        "Collect next frameno's digits until `enter` is pressed."
        if event.key.isnumeric():
            self.frameno_input += event.key
        elif event.key == "enter":
            self.frameno = min(int(self.frameno_input or self.frameno),
                               self.num_frames-1)
            self.plot_and_cache(self.frameno)
            self.frameno_input = ""
            print("\n"+self.prompt, end=" ")
```

**Comment by mandli** [comment]
Do you want to issue a PR for those changes so that we can test them out?  We can also snag the arguments from the make command given and pass them to Python.  That then brings up adding a better CLI to `ipyclaw`.  Once this is done we can test and then add a PR for clawutil for `Makefile.common`.
