### ISSUE TITLE
Matplotlib `RuntimeWarning` exception:  Too many figures open simultaneously

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#75]
Newer versions of Matplotlib seem to now show the following warning when plotting more than `20` figures:

```
RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_num_figures`).
  max_open_warning, RuntimeWarning)
```

This usually only happens while making the JSAnimation movies I think (or of course if you have more than twenty plots).

**Comment by freeleons** [comment]
Try setting it this way:

import matplotlib as plt 
plt.rcParams.update({'figure.max_open_warning': 0})

Not sure exactly why this works, but it mirrors the way I have changed the font size in the past and seems to fix the warnings for me.

**Comment by mandli** [comment]
Thanks for the pointer!  They must have changed this at some point.
