### ISSUE TITLE
HTML frame title time does not match figure time

### ISSUE THREAD

**Issue by mandli** [clawpack/visclaw#83]
@mjberger reported that she saw the weirdness in the following images.  The time in the plot title is incorrect.

The following bug/typo is showing up in the advection_2d_swirl directory that i"ve been working with today.

![pastedgraphic-4](https://f.cloud.github.com/assets/322129/1161151/89a4c36e-1fe6-11e3-8959-a05a74777434.png)

The PlotIndex says for example that  Frame 8 is at t=4.0000:

![pastedgraphic-3](https://f.cloud.github.com/assets/322129/1161153/8d42aee6-1fe6-11e3-9e90-ad128a26bb16.png)
But when you click on Frame 8 it says 2 conflicting things. The plot title is wrong and the page title is right.

**Comment by ketch** [comment]
I'm going to close this; we can reopen it if there is an example that reproduces the bug.
