### ISSUE TITLE
git_resources page full of broken links

### ISSUE THREAD

**Issue by ketch** [clawpack/visclaw#92]
When I build the docs, I see a lot of warnings for git_resources.html and the page is full of broken refs.

**Comment by rjleveque** [comment]
See clawpack/doc#88.

**Comment by ketch** [comment]
I suggest that we delete `git_resources.rst` altogether, because:

- The links will continue to break;
- The links will be superseded by better material available elsewhere on the internet;
- A host of excellent resources can be found by simple Google search;
- Removing this page will save developer time.

**Comment by rjleveque** [comment]
Done.
